name: Build and Test
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
# 1. When should this run?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. What should it do?
jobs:
  build:
    runs-on: ubuntu-latest # The temporary server environment

    steps:
    # Pulls your code from the repository
    - uses: actions/checkout@v4 

    # Installs the SDK (e.g., .NET 8)
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    # Compiles the code
    - name: Build project
      run: dotnet build
